const axios = require('axios');

const sendToSlack = async (summary, todoCount = 0) => {
    try {
        const currentTime = new Date().toLocaleString('en-US', {
            weekday: 'long',
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
            timeZoneName: 'short'
        });

        // Create rich Slack message with blocks
        const slackMessage = {
            text: `📋 Todo Summary Report - ${todoCount} Pending Task${todoCount !== 1 ? 's' : ''}`,
            blocks: [
                {
                    type: "header",
                    text: {
                        type: "plain_text",
                        text: "📋 Todo Summary Report",
                        emoji: true
                    }
                },
                {
                    type: "context",
                    elements: [
                        {
                            type: "mrkdwn",
                            text: `📊 *${todoCount}* pending task${todoCount !== 1 ? 's' : ''} analyzed • Generated on ${currentTime}`
                        }
                    ]
                },
                {
                    type: "divider"
                },
                {
                    type: "section",
                    text: {
                        type: "mrkdwn",
                        text: summary
                    }
                },
                {
                    type: "divider"
                },
                {
                    type: "context",
                    elements: [
                        {
                            type: "mrkdwn",
                            text: "🤖 _Generated by Todo Summary Assistant with AI-powered analysis_"
                        }
                    ]
                },
                {
                    type: "actions",
                    elements: [
                        {
                            type: "button",
                            text: {
                                type: "plain_text",
                                text: "View Todo App",
                                emoji: true
                            },
                            value: "view_app",
                            url: process.env.FRONTEND_URL || "http://localhost:3000",
                            style: "primary"
                        }
                    ]
                }
            ]
        };

        console.log('📤 Sending message to Slack...');
        
        const response = await axios.post(process.env.SLACK_WEBHOOK_URL, slackMessage, {
            headers: {
                'Content-Type': 'application/json'
            }
        });

        if (response.status === 200) {
            console.log('✅ Message sent to Slack successfully');
        } else {
            throw new Error(`Slack API returned status ${response.status}`);
        }
        
    } catch (error) {
        console.error('❌ Error sending to Slack:', error.response?.data || error.message);
        
        // Handle different types of Slack errors
        if (error.response?.status === 404) {
            throw new Error('Slack webhook URL not found. Please check your webhook URL.');
        } else if (error.response?.status === 400) {
            throw new Error('Slack webhook request was invalid. Please check the webhook configuration.');
        } else if (error.code === 'ENOTFOUND') {
            throw new Error('Could not connect to Slack. Please check your internet connection.');
        } else {
            throw new Error(`Slack integration error: ${error.message}`);
        }
    }
};

// Test function to verify Slack webhook is working
const testSlackConnection = async () => {
    try {
        const testMessage = {
            text: "🧪 Test message from Todo Summary Assistant",
            blocks: [
                {
                    type: "section",
                    text: {
                        type: "mrkdwn",
                        text: "✅ *Slack integration is working correctly!*\n\nThis is a test message to verify the webhook connection."
                    }
                }
            ]
        };

        await axios.post(process.env.SLACK_WEBHOOK_URL, testMessage);
        console.log('✅ Slack test message sent successfully');
        return true;
    } catch (error) {
        console.error('❌ Slack test failed:', error.message);
        return false;
    }
};

module.exports = {
    sendToSlack,
    testSlackConnection
};